In [7]:
pip install gitpython

Requirement already satisfied: gitpython in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.46)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from gitpython) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import git
repo_path="https://github.com/PhonePe/pulse.git"
destination_path=r"C:\Users\DELL\OneDrive\Desktop\phonepe_project"
git.Repo.clone_from(repo_path,destination_path)
print("Done clonning")

GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/PhonePe/pulse.git C:\Users\DELL\OneDrive\Desktop\phonepe_project
  stderr: 'fatal: destination path 'C:\Users\DELL\OneDrive\Desktop\phonepe_project' already exists and is not an empty directory.
'

In [ ]:
import pandas as pd
import json
import os

path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/aggregated/transaction/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [11]:
data_collection_transaction={'State':[],'Year':[],'Quarter':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

In [12]:
data_collection_transaction

{'State': [],
 'Year': [],
 'Quarter': [],
 'Transaction_type': [],
 'Transaction_count': [],
 'Transaction_amount': []}

In [13]:
for i in Agg_state_list:
    p_i=path+i+"/"
    agg_yr=os.listdir(p_i)
    for j in agg_yr:
        p_j=p_i+j+"/"
        agg_yr_list=os.listdir(p_j)
        for k in agg_yr_list:
            p_k=p_j+k
            data=open(p_k,'r')
            dataset=json.load(data)
            for z in dataset['data']['transactionData']:
                name=z['name']
                count=z['paymentInstruments'][0]['count']
                amount=z['paymentInstruments'][0]['amount']
                data_collection_transaction['Transaction_type'].append(name)
                data_collection_transaction['Transaction_count'].append(count)
                data_collection_transaction['Transaction_amount'].append(amount)
                data_collection_transaction['State'].append(i)
                data_collection_transaction['Year'].append(j)
                data_collection_transaction['Quarter'].append(int(k.strip('.json')))

Agg_transaction=pd.DataFrame(data_collection_transaction)
Agg_transaction.drop_duplicates()

Agg_transaction["State"] = Agg_transaction["State"].str.replace("-", " ")
Agg_transaction["State"] = Agg_transaction["State"].str.title()
Agg_transaction["State"] = Agg_transaction["State"].str.strip()
Agg_transaction

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar Islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar Islands,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar Islands,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar Islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,West Bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,West Bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,West Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West Bengal,2024,4,Others,421806,5.053641e+08

In [ ]:
import mysql.connector


conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()


insert_query = """
INSERT IGNORE INTO aggregated_transaction
(state, year, quarter, transaction_type, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""
for _, row in Agg_transaction.iterrows():
    cursor.execute(insert_query, (
        row['State'],
        row['Year'],
        row['Quarter'],
        row['Transaction_type'],
        row['Transaction_count'],
        row['Transaction_amount']
    ))

conn.commit()

cursor.close()
conn.close()

print("Inserted successfully ✅")

In [15]:
import pandas as pd
import json
import os



path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/aggregated/insurance/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [16]:
data_collection_insurance={'State':[],'Year':[],'Quarter':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

In [17]:
for i in Agg_state_list:
    p_i=path+i+"/"
    agg_yr=os.listdir(p_i)
    for j in agg_yr:
        p_j=p_i+j+"/"
        agg_yr_list=os.listdir(p_j)
        for k in agg_yr_list:
            p_k=p_j+k
            data=open(p_k,'r')
            dataset=json.load(data)
            for z in dataset['data']['transactionData']:
                name=z['name']
                count=z['paymentInstruments'][0]['count']
                amount=z['paymentInstruments'][0]['amount']
                data_collection_insurance['Transaction_type'].append(name)
                data_collection_insurance['Transaction_count'].append(count)
                data_collection_insurance['Transaction_amount'].append(amount)
                data_collection_insurance['State'].append(i)
                data_collection_insurance['Year'].append(j)
                data_collection_insurance['Quarter'].append(int(k.strip('.json')))

In [18]:
agg_insurance=pd.DataFrame(data_collection_insurance)
agg_insurance=agg_insurance.drop_duplicates()
agg_insurance["State"] = agg_insurance["State"].str.replace("-", " ")
agg_insurance["State"] = agg_insurance["State"].str.title()
agg_insurance["State"] = agg_insurance["State"].str.strip()
agg_insurance

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar Islands,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar Islands,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar Islands,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar Islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,West Bengal,2023,4,Insurance,72712,100365562.0
678,West Bengal,2024,1,Insurance,79576,104987909.0
679,West Bengal,2024,2,Insurance,67048,89476633.0
680,West Bengal,2024,3,Insurance,77158,107451766.0
681,West Bengal,2024,4,Insurance,91719,120602777.0

In [ ]:
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

# Insert query
insert_query = """
INSERT IGNORE INTO aggregated_insurance
(state, year, quarter, transaction_type, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

# Loop through dataframe rows
for i, row in agg_insurance.iterrows():
    values = (
        row['State'],
        int(row['Year']),
        int(row['Quarter']),
        row['Transaction_type'],
        int(row['Transaction_count']),
        float(row['Transaction_amount'])
    )
    
    cursor.execute(insert_query, values)

# Commit changes
conn.commit()

# Close connection
cursor.close()
conn.close()

print("Data inserted successfully ✅")

In [19]:
import pandas as pd
import json
import os


#path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/aggregated/transaction/country/india/state/"
#path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/aggregated/insurance/country/india/state/"
path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/aggregated/user/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [20]:
data_collection_user={'State':[],'Year':[],'Quarter':[],'brand':[],'count':[],'percentage':[]}

In [21]:
for i in Agg_state_list:
    p_i=path+i+"/"
    agg_yr=os.listdir(p_i)
    for j in agg_yr:
        p_j=p_i+j+"/"
        agg_yr_list = sorted(os.listdir(p_j))

        for k in agg_yr_list:
            p_k = p_j + k
            data = open(p_k, 'r')
            dataset = json.load(data)

            users = dataset.get('data', {}).get('usersByDevice', [])

            quarter = int(k.replace('.json', ''))

            if users:
                for z in users:
                    data_collection_user['brand'].append(z.get('brand'))
                    data_collection_user['count'].append(z.get('count'))
                    data_collection_user['percentage'].append(z.get('percentage'))
                    data_collection_user['State'].append(i)
                    data_collection_user['Year'].append(j)
                    data_collection_user['Quarter'].append(quarter)
                    

    
agg_user=pd.DataFrame(data_collection_user)
agg_user = agg_user.drop_duplicates()
agg_user["State"] = agg_user["State"].str.replace("-", " ")
agg_user["State"] = agg_user["State"].str.title()
agg_user["State"] = agg_user["State"].str.strip()

In [22]:

agg_user

                          State  Year  Quarter    brand    count  percentage
0     Andaman & Nicobar Islands  2018        1   Xiaomi     1665    0.247033
1     Andaman & Nicobar Islands  2018        1  Samsung     1445    0.214392
2     Andaman & Nicobar Islands  2018        1     Vivo      982    0.145697
3     Andaman & Nicobar Islands  2018        1     Oppo      501    0.074332
4     Andaman & Nicobar Islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                West Bengal  2022        1   Lenovo   330017    0.015056
6728                West Bengal  2022        1  Infinix   284678    0.012987
6729                West Bengal  2022        1     Asus   280347    0.012790
6730                West Bengal  2022        1    Apple   277752    0.012671
6731                West Bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]

In [ ]:
import mysql.connector


conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()


insert_query = """
INSERT INTO aggregated_user
(state, year, quarter, brand, user_count, percentage)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
user_count = VALUES(user_count),
percentage = VALUES(percentage)
"""


data = []

for i, row in agg_user.iterrows():
    data.append((
        row['State'],
        int(row['Year']),
        int(row['Quarter']),
        row['brand'],
        int(row['count']),
        float(row['percentage'])
    ))

cursor.executemany(insert_query, data)


conn.commit()


cursor.close()
conn.close()

print("Aggregated User Data Inserted ✅")

In [ ]:
q2_data = agg_user[agg_user['Quarter'] == 2]
q2_data

In [24]:
path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/map/insurance/hover/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [25]:
data_map_insurance = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'name': [],
    'count': [],
    'amount': []
}

for i in Agg_state_list:
    p_i = path + i + "/"
    agg_yr = os.listdir(p_i)

    for j in agg_yr:
        p_j = p_i + j + "/"
        agg_yr_list = sorted(os.listdir(p_j))

        for k in agg_yr_list:
            p_k = p_j + k

            with open(p_k, 'r') as data:
                dataset = json.load(data)

            hover = dataset.get('data', {}).get('hoverDataList', [])

            quarter = int(k.replace('.json', ''))

            if hover:
                for z in hover:
                    metric = z.get('metric', [])

                    if metric:
                        data_map_insurance['name'].append(z.get('name'))
                        data_map_insurance['count'].append(metric[0].get('count'))
                        data_map_insurance['amount'].append(metric[0].get('amount'))
                        data_map_insurance['State'].append(i)
                        data_map_insurance['Year'].append(j)
                        data_map_insurance['Quarter'].append(quarter)

data_map_insurance = pd.DataFrame(data_map_insurance)
data_map_insurance.drop_duplicates()
data_map_insurance["State"] = data_map_insurance["State"].str.replace("-", " ")
data_map_insurance["State"] = data_map_insurance["State"].str.title()
data_map_insurance["State"] = data_map_insurance["State"].str.strip()
data_map_insurance["name"] = data_map_insurance["name"].str.replace("-", " ")
data_map_insurance["name"] = data_map_insurance["name"].str.title()
data_map_insurance["name"] = data_map_insurance["name"].str.strip()
data_map_insurance

,State,Year,Quarter,name,count,amount
0,Andaman & Nicobar Islands,2020,2,South Andaman District,3,795.0
1,Andaman & Nicobar Islands,2020,2,Nicobars District,3,565.0
2,Andaman & Nicobar Islands,2020,3,North And Middle Andaman District,1,281.0
3,Andaman & Nicobar Islands,2020,3,South Andaman District,35,13651.0
4,Andaman & Nicobar Islands,2020,3,Nicobars District,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,Alipurduar District,1023,1613143.0
13872,West Bengal,2024,4,Paschim Bardhaman District,4945,7005851.0
13873,West Bengal,2024,4,Nadia District,3807,5031294.0
13874,West Bengal,2024,4,Birbhum District,1818,2423290.0
13875,West Bengal,2024,4,Purba Medinipur District,3559,4439061.0

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

insert_query = """
INSERT INTO map_insurance
(state, year, quarter, district, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""

data = []

for i, row in data_map_insurance.iterrows():
    data.append((
        row['State'],
        int(row['Year']),
        int(row['Quarter']),
        row['name'],              
        int(row['count']),
        float(row['amount'])
    ))


cursor.executemany(insert_query, data)

conn.commit()

cursor.close()
conn.close()

print("Map Insurance Data Inserted ")

In [26]:
map_transact_path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/map/transaction/hover/country/india/state/"
Agg_state_list_map_transact=os.listdir(map_transact_path)
Agg_state_list_map_transact

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [27]:
data_map_transact= {
    'State': [],
    'Year': [],
    'Quarter': [],
    'name': [],
    'count': [],
    'amount': []
}

for i in Agg_state_list_map_transact:
    p_i = map_transact_path + i + "/"
    agg_yr = os.listdir(p_i)

    for j in agg_yr:
        p_j = p_i + j + "/"
        agg_yr_list = sorted(os.listdir(p_j))

        for k in agg_yr_list:
            p_k = p_j + k

            with open(p_k, 'r') as data:
                dataset = json.load(data)

            hover = dataset.get('data', {}).get('hoverDataList', [])

            quarter = int(k.replace('.json', ''))

            if hover:
                for z in hover:
                    metric = z.get('metric', [])

                    if metric:
                        data_map_transact['name'].append(z.get('name'))
                        data_map_transact['count'].append(metric[0].get('count'))
                        data_map_transact['amount'].append(metric[0].get('amount'))
                        data_map_transact['State'].append(i)
                        data_map_transact['Year'].append(j)
                        data_map_transact['Quarter'].append(quarter)

data_map_transact = pd.DataFrame(data_map_transact)
data_map_transact.drop_duplicates()
data_map_transact["State"] = data_map_transact["State"].str.replace("-", " ")
data_map_transact["State"] = data_map_transact["State"].str.title()
data_map_transact["State"] = data_map_transact["State"].str.strip()
data_map_transact["name"] = data_map_transact["name"].str.replace("-", " ")
data_map_transact["name"] = data_map_transact["name"].str.title()
data_map_transact["name"] = data_map_transact["name"].str.strip()
data_map_transact

,State,Year,Quarter,name,count,amount
0,Andaman & Nicobar Islands,2018,1,North And Middle Andaman District,442,9.316631e+05
1,Andaman & Nicobar Islands,2018,1,South Andaman District,5688,1.256025e+07
2,Andaman & Nicobar Islands,2018,1,Nicobars District,528,1.139849e+06
3,Andaman & Nicobar Islands,2018,2,North And Middle Andaman District,825,1.317863e+06
4,Andaman & Nicobar Islands,2018,2,South Andaman District,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West Bengal,2024,4,Alipurduar District,15875637,2.099251e+10
20600,West Bengal,2024,4,Paschim Bardhaman District,56616799,6.968735e+10
20601,West Bengal,2024,4,Nadia District,65274337,1.079320e+11
20602,West Bengal,2024,4,Birbhum District,36905213,5.778701e+10
20603,West Bengal,2024,4,Purba Medinipur District,67833775,1.142771e+11

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

query = """
INSERT INTO map_transaction
(state, year, quarter, district, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""

data = [
    (
        row["State"],
        int(row["Year"]),
        int(row["Quarter"]),
        row["name"],   
        int(row["count"]),
        float(row["amount"])
    )
    for _, row in data_map_transact.iterrows()
]

cursor.executemany(query, data)
conn.commit()

cursor.close()
conn.close()

print(" District data inserted successfully")

In [ ]:
import json
import os

base_path = "C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/map/transaction/hover/country/india/"


data_map_transact_state = {
    "State": [],
    "Year": [],
    "Quarter": [],
    "Transaction_count": [],
    "Transaction_amount": []
}

data_map_transact_district = {
    "State": [],
    "Year": [],
    "Quarter": [],
    "District": [],
    "Transaction_count": [],
    "Transaction_amount": []
}


for year in os.listdir(base_path):

    year_path = base_path + year + "/"

    
    for file in os.listdir(year_path):

        if file.endswith(".json"):
            quarter = int(file.strip(".json"))

            with open(year_path + file, "r") as f:
                data = json.load(f)

            
            for item in data["data"]["hoverDataList"]:
                metric = item.get("metric", [])

                if metric:
                    data_map_transact_state["State"].append(item.get("name"))
                    data_map_transact_state["Year"].append(int(year))
                    data_map_transact_state["Quarter"].append(quarter)
                    data_map_transact_state["Transaction_count"].append(metric[0].get("count"))
                    data_map_transact_state["Transaction_amount"].append(metric[0].get("amount"))

    
    state_folder_path = base_path + "state/"

    for state in os.listdir(state_folder_path):

        state_path = state_folder_path + state + "/" + year + "/"

        if not os.path.exists(state_path):
            continue

        for file in os.listdir(state_path):

            if file.endswith(".json"):
                quarter = int(file.strip(".json"))

                with open(state_path + file, "r") as f:
                    data = json.load(f)

                for item in data["data"]["hoverDataList"]:
                    metric = item.get("metric", [])

                    if metric:
                        data_map_transact_district["State"].append(state)
                        data_map_transact_district["Year"].append(int(year))
                        data_map_transact_district["Quarter"].append(quarter)
                        data_map_transact_district["District"].append(item.get("name"))
                        data_map_transact_district["Transaction_count"].append(metric[0].get("count"))
                        data_map_transact_district["Transaction_amount"].append(metric[0].get("amount"))


data_map_transact_state

 Extraction Completed

In [29]:
data_map_transact_state=pd.DataFrame(data_map_transact_state)
data_map_transact_state.drop_duplicates()
data_map_transact_state["State"] = data_map_transact_state["State"].str.replace("-", " ")
data_map_transact_state["State"] = data_map_transact_state["State"].str.title()
data_map_transact_state["State"] = data_map_transact_state["State"].str.strip()
data_map_transact_state

                  State  Year  Quarter  Transaction_count  Transaction_amount
0            Puducherry  2018        1             104212        1.658260e+08
1            Tamil Nadu  2018        1            6726622        1.126156e+10
2         Uttar Pradesh  2018        1           12537805        1.393997e+10
3        Madhya Pradesh  2018        1            8025395        8.681603e+09
4        Andhra Pradesh  2018        1            9039585        1.199628e+10
...                 ...   ...      ...                ...                 ...
1003    Jammu & Kashmir  2024        4          126261217        1.609510e+11
1004                Goa  2024        4           46131536        5.656259e+10
1005  Arunachal Pradesh  2024        4           26793457        3.507989e+10
1006              Delhi  2024        4          910543082        1.057060e+12
1007        Uttarakhand  2024        4          171136132        1.949088e+11

[1008 rows x 5 columns]

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

query_state = """
INSERT INTO map_transaction_state
(state, year, quarter, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""
data_state = [
    (
        row["State"],
        int(row["Year"]),
        int(row["Quarter"]),
        int(row["Transaction_count"]),
        float(row["Transaction_amount"])
    )
    for _, row in data_map_transact_state.iterrows()
]

cursor.executemany(query_state, data_state)
conn.commit()

print(" State data inserted")

In [30]:

data_map_transact_district=pd.DataFrame(data_map_transact_district)
data_map_transact_district.drop_duplicates()
data_map_transact_district["State"] = data_map_transact_district["State"].str.replace("-", " ")
data_map_transact_district["State"] = data_map_transact_district["State"].str.title()
data_map_transact_district["State"] = data_map_transact_district["State"].str.strip()
data_map_transact_district

data_map_transact_district["District"] = data_map_transact_district["District"].str.replace("-", " ")
data_map_transact_district["District"] = data_map_transact_district["District"].str.title()
data_map_transact_district["District"] = data_map_transact_district["District"].str.strip()
data_map_transact_district

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2018,1,North And Middle Andaman District,442,9.316631e+05
1,Andaman & Nicobar Islands,2018,1,South Andaman District,5688,1.256025e+07
2,Andaman & Nicobar Islands,2018,1,Nicobars District,528,1.139849e+06
3,Andaman & Nicobar Islands,2018,2,North And Middle Andaman District,825,1.317863e+06
4,Andaman & Nicobar Islands,2018,2,South Andaman District,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West Bengal,2024,4,Alipurduar District,15875637,2.099251e+10
20600,West Bengal,2024,4,Paschim Bardhaman District,56616799,6.968735e+10
20601,West Bengal,2024,4,Nadia District,65274337,1.079320e+11
20602,West Bengal,2024,4,Birbhum District,36905213,5.778701e+10
20603,West Bengal,2024,4,Purba Medinipur District,67833775,1.142771e+11

In [ ]:
insert_query = """
INSERT INTO map_transaction_district
(state, district, year, quarter, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""

data = [
    (
        row["State"],
        row["District"],
        int(row["Year"]),
        int(row["Quarter"]),
        int(row["Transaction_count"]),
        float(row["Transaction_amount"])
    )
    for _, row in data_map_transact_district.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()

In [32]:
import pandas as pd


data_map_transact_state["Level"] = "State"
data_map_transact_district["Level"] = "District"


data_map_transact_state = data_map_transact_state.rename(columns={
    "Transaction_count": "Transaction_count",
    "Transaction_amount": "Transaction_amount"
})

data_map_transact_district = data_map_transact_district.rename(columns={
    "Transaction_count": "Transaction_count",
    "Transaction_amount": "Transaction_amount"
})


data_map_transact_state["District"] = None


data_map_transact_state = data_map_transact_state[
    ["State", "Year", "Quarter", "District", "Transaction_count", "Transaction_amount", "Level"]
]

data_map_transact_district = data_map_transact_district[
    ["State", "Year", "Quarter", "District", "Transaction_count", "Transaction_amount", "Level"]
]


combined_df = pd.concat([data_map_transact_state, data_map_transact_district], ignore_index=True)

combined_df.head()

,State,Year,Quarter,District,Transaction_count,Transaction_amount,Level
0,Puducherry,2018,1,None,104212,1.658260e+08,State
1,Tamil Nadu,2018,1,None,6726622,1.126156e+10,State
2,Uttar Pradesh,2018,1,None,12537805,1.393997e+10,State
3,Madhya Pradesh,2018,1,None,8025395,8.681603e+09,State
4,Andhra Pradesh,2018,1,None,9039585,1.199628e+10,State

In [34]:
df = combined_df.copy()


df = df.drop_duplicates()


df["State"] = df["State"].str.replace("-", " ")
df["State"] = df["State"].str.title().str.strip()


df["District"] = df["District"].fillna("All")
df["District"] = df["District"].astype(str)
df["District"] = df["District"].str.replace("-", " ")
df["District"] = df["District"].str.title().str.strip()


df["Level"] = df["Level"].str.title().str.strip()

In [ ]:
insert_query = """
INSERT INTO map_transaction_combined
(state, district, year, quarter, transaction_count, transaction_amount, level)
VALUES (%s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""

data = [
    (
        row["State"],
        row["District"] if row["District"] else "All",
        int(row["Year"]),
        int(row["Quarter"]),
        int(row["Transaction_count"]),
        float(row["Transaction_amount"]),
        row["Level"]
    )
    for _, row in df.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()

print(" Combined data inserted correctly")

In [35]:
map_user_path=r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\map\user\hover\country\india\state/"
Agg_state_list_map_user=os.listdir(map_user_path)
Agg_state_list_map_user

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [36]:
data_map_user = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'name': [],
    'registeredUsers': [],
    'appOpens': []
}

for i in Agg_state_list_map_user:
    p_i = map_user_path + i + "/"
    agg_yr = os.listdir(p_i)

    for j in agg_yr:
        p_j = p_i + j + "/"
        agg_yr_list = sorted(os.listdir(p_j))

        for k in agg_yr_list:
            p_k = p_j + k

            with open(p_k, 'r') as data:
                dataset = json.load(data)

            hover = dataset.get('data', {}).get('hoverData', {})

            quarter = int(k.replace('.json', ''))

            if hover:
                for name, val in hover.items():   
                    data_map_user['name'].append(name)
                    data_map_user['registeredUsers'].append(val.get('registeredUsers'))
                    data_map_user['appOpens'].append(val.get('appOpens'))
                    data_map_user['State'].append(i)
                    data_map_user['Year'].append(j)
                    data_map_user['Quarter'].append(quarter)

data_map_user = pd.DataFrame(data_map_user)
data_map_user.drop_duplicates()

data_map_user

,State,Year,Quarter,name,registeredUsers,appOpens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [37]:
df = pd.DataFrame(data_map_user)


df = df.drop_duplicates()


df["State"] = df["State"].str.replace("-", " ")
df["State"] = df["State"].str.title().str.strip()


df["name"] = df["name"].astype(str)
df["name"] = df["name"].str.replace("-", " ")
df["name"] = df["name"].str.title().str.strip()
df

,State,Year,Quarter,name,registeredUsers,appOpens
0,Andaman & Nicobar Islands,2018,1,North And Middle Andaman District,632,0
1,Andaman & Nicobar Islands,2018,1,South Andaman District,5846,0
2,Andaman & Nicobar Islands,2018,1,Nicobars District,262,0
3,Andaman & Nicobar Islands,2018,2,North And Middle Andaman District,911,0
4,Andaman & Nicobar Islands,2018,2,South Andaman District,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,Alipurduar District,475688,31842355
20604,West Bengal,2024,4,Paschim Bardhaman District,1468252,80543469
20605,West Bengal,2024,4,Nadia District,1861738,98740305
20606,West Bengal,2024,4,Birbhum District,1114220,73465525
20607,West Bengal,2024,4,Purba Medinipur District,1717074,108350777

In [38]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

insert_query = """
INSERT INTO map_user
(state, district, year, quarter, registered_users, app_opens)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
registered_users = VALUES(registered_users),
app_opens = VALUES(app_opens)
"""
data = [
    (
        row["State"],                  
        row["name"],                   
        int(row["Year"]),              
        int(row["Quarter"]),           
        int(row["registeredUsers"]),
        int(row["appOpens"])
    )
    for _, row in df.iterrows()
]
cursor.executemany(insert_query,data)
conn.commit()

cursor.close()
conn.close()

print(" Map User District data inserted successfully")

 Map User District data inserted successfully

In [40]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()
base_path = "data/map/user/hover/country/india/state"

for state_folder in os.listdir(base_path):
    state_path = os.path.join(base_path, state_folder)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for quarter_file in os.listdir(year_path):
            quarter = quarter_file.replace(".json", "")

            with open(os.path.join(year_path, quarter_file)) as f:
                data = json.load(f)

                for state in data["data"]["hoverData"]:
                    registered = data["data"]["hoverData"][state]["registeredUsers"]
                    opens = data["data"]["hoverData"][state]["appOpens"]

                    cursor.execute("""
                        INSERT INTO map_users
                        (year, quarter, state, registered_users, app_opens)
                        VALUES (%s, %s, %s, %s, %s)
                    """, (int(year), int(quarter), state, int(registered), int(opens)))

In [41]:
top_insurance_path="C:/Users/DELL/OneDrive/Desktop/phonepe_project/data/top/insurance/country/india/state/"
Agg_state_list_top_insure=os.listdir(top_insurance_path)
Agg_state_list_top_insure

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [44]:
import os
import json
import pandas as pd

top_insurance_state_path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\insurance\country\india"

data_state = {
    'Year': [],
    'Quarter': [],
    'state': [],
    'count': [],
    'amount': []
}

years = os.listdir(top_insurance_state_path)

for j in years:
    p_j = os.path.join(top_insurance_state_path, j)

    if not os.path.isdir(p_j):
        continue

    files = sorted(os.listdir(p_j))

    for k in files:
        if not k.endswith('.json'):
            continue

        p_k = os.path.join(p_j, k)

        with open(p_k, 'r') as data:
            dataset = json.load(data)

        states = dataset.get('data', {}).get('states', [])
        quarter = int(k.replace('.json', ''))

        for z in states:
            metric = z.get('metric', {})

            data_state['state'].append(z.get('entityName'))
            data_state['count'].append(metric.get('count'))
            data_state['amount'].append(metric.get('amount'))
            data_state['Year'].append(j)
            data_state['Quarter'].append(quarter)

data_state = pd.DataFrame(data_state).drop_duplicates()
data_state.drop_duplicates()
data_state["state"] = data_state["state"].str.replace("-", " ")
data_state["state"] = data_state["state"].str.title()
data_state["state"] = data_state["state"].str.strip()
data_state
df = data_state[[
    "state",
    "Year",
    "Quarter",
    "count",
    "amount"
]]

In [45]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()
insert_query = """
INSERT INTO top_insurance_state
(state, year, quarter, insurance_count, insurance_amount)
VALUES (%s, %s, %s, %s, %s)

ON DUPLICATE KEY UPDATE
insurance_count = VALUES(insurance_count),
insurance_amount = VALUES(insurance_amount)
"""
data = [
    (
        str(row["state"]),        
        int(row["Year"]),         
        int(row["Quarter"]),      
        int(row["count"]),     
        float(row["amount"])      
                )
    for _, row in df.iterrows()
]
cursor.executemany(insert_query, data)
conn.commit()

cursor.close()
conn.close()

print("✅ Top Insurance State data inserted successfully")

✅ Top Insurance State data inserted successfully

In [47]:
top_insurance_district_path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\insurance\country\india\state"

data_district = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'district': [],
    'count': [],
    'amount': []
}

states_list = os.listdir(top_insurance_district_path)

for i in states_list:
    p_i = os.path.join(top_insurance_district_path, i)

    if not os.path.isdir(p_i):
        continue

    years = os.listdir(p_i)

    for j in years:
        p_j = os.path.join(p_i, j)

        if not os.path.isdir(p_j):
            continue

        files = sorted(os.listdir(p_j))

        for k in files:
            if not k.endswith('.json'):
                continue

            p_k = os.path.join(p_j, k)

            with open(p_k, 'r') as data:
                dataset = json.load(data)

            districts = dataset.get('data', {}).get('districts', [])
            quarter = int(k.replace('.json', ''))

            for z in districts:
                metric = z.get('metric', {})

                data_district['district'].append(z.get('entityName'))
                data_district['count'].append(metric.get('count'))
                data_district['amount'].append(metric.get('amount'))
                data_district['State'].append(i)
                data_district['Year'].append(j)
                data_district['Quarter'].append(quarter)

data_district = pd.DataFrame(data_district).drop_duplicates()
data_district.drop_duplicates()
data_district["State"] = data_district["State"].str.replace("-", " ")
data_district["State"] = data_district["State"].str.title()
data_district["State"] = data_district["State"].str.strip()
data_district

,State,Year,Quarter,district,count,amount
0,Andaman & Nicobar Islands,2020,2,nicobars,3,565.0
1,Andaman & Nicobar Islands,2020,2,south andaman,3,795.0
2,Andaman & Nicobar Islands,2020,3,south andaman,35,13651.0
3,Andaman & Nicobar Islands,2020,3,nicobars,5,1448.0
4,Andaman & Nicobar Islands,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,West Bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,West Bengal,2024,4,paschim medinipur,4155,5405054.0
5605,West Bengal,2024,4,malda,4042,4902098.0
5606,West Bengal,2024,4,nadia,3807,5031294.0
5607,West Bengal,2024,4,purba bardhaman,3595,4482879.0

In [ ]:
df = data_district[[
    "State",
    "district",
    "Year",
    "Quarter",
    "count",
    "amount"
]]

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()
insert_query = """
INSERT INTO top_insurance_district
(state, district, year, quarter, insurance_count, insurance_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
insurance_count = VALUES(insurance_count),
insurance_amount = VALUES(insurance_amount)
"""
data = [
    (
        str(row["State"]),          
        str(row["district"]),       
        int(row["Year"]),           
        int(row["Quarter"]),      
        int(row["count"]),          
        float(row["amount"])        
    )
    for _, row in df.iterrows()
]
cursor.executemany(insert_query, data)
conn.commit()

cursor.close()
conn.close()

print("✅ Top Insurance District data inserted successfully")

In [48]:
top_insurance_path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\insurance\country\india\state/"
Agg_state_list = os.listdir(top_insurance_district_path)
data_top_insurance_pincode = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'pincode': [],
    'count': [],
    'amount': []
}

for i in Agg_state_list:
    p_i = top_insurance_path + i + "/"
    agg_yr = os.listdir(p_i)

    for j in agg_yr:
        p_j = p_i + j + "/"
        agg_yr_list = sorted(os.listdir(p_j))

        for k in agg_yr_list:
            p_k = p_j + k

            with open(p_k, 'r') as data:
                dataset = json.load(data)

            pincodes = dataset.get('data', {}).get('pincodes', [])
            quarter = int(k.replace('.json', ''))

            if pincodes:
                for z in pincodes:
                    metric = z.get('metric', {})

                    data_top_insurance_pincode['pincode'].append(z.get('entityName'))
                    data_top_insurance_pincode['count'].append(metric.get('count'))
                    data_top_insurance_pincode['amount'].append(metric.get('amount'))
                    data_top_insurance_pincode['State'].append(i)
                    data_top_insurance_pincode['Year'].append(j)
                    data_top_insurance_pincode['Quarter'].append(quarter)

data_top_insurance_pincode = pd.DataFrame(data_top_insurance_pincode)
data_top_insurance_pincode.drop_duplicates()
data_top_insurance_pincode
data_top_insurance_pincode["count"].fillna(0, inplace=True)
data_top_insurance_pincode["amount"].fillna(0, inplace=True)
data_top_insurance_pincode["State"] = data_top_insurance_pincode["State"].str.replace("-", " ")
data_top_insurance_pincode["State"] = data_top_insurance_pincode["State"].str.title()
data_top_insurance_pincode["State"] = data_top_insurance_pincode["State"].str.strip()
data_top_insurance_pincode

                          State  Year  Quarter pincode  count    amount
0     Andaman & Nicobar Islands  2020        2  744301      3     565.0
1     Andaman & Nicobar Islands  2020        2  744104      2     513.0
2     Andaman & Nicobar Islands  2020        2  744101      1     282.0
3     Andaman & Nicobar Islands  2020        3  744112      9    3432.0
4     Andaman & Nicobar Islands  2020        3  744105      7    3948.0
...                         ...   ...      ...     ...    ...       ...
6663                West Bengal  2024        4  711101    713  750354.0
6664                West Bengal  2024        4  700091    642  969634.0
6665                West Bengal  2024        4  700150    627  761501.0
6666                West Bengal  2024        4  700039    619  787836.0
6667                West Bengal  2024        4  700156    574  888613.0

[6668 rows x 6 columns]

In [49]:
df = data_top_insurance_pincode.copy()

df = df[[
    "State", "Year", "Quarter",
    "pincode", "count", "amount"
]]

# Convert safely
df["pincode"] = pd.to_numeric(df["pincode"], errors="coerce")
df["count"] = pd.to_numeric(df["count"], errors="coerce")
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

# Drop bad rows
df = df.dropna()

# Convert types
df["pincode"] = df["pincode"].astype(int)
df["count"] = df["count"].astype(int)
df["amount"] = df["amount"].astype(float)
df["Year"] = df["Year"].astype(int)
df["Quarter"] = df["Quarter"].astype(int)

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

insert_query = """
INSERT INTO top_insurance_pincode
(state, year, quarter, pincode, insurance_count, insurance_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
insurance_count = VALUES(insurance_count),
insurance_amount = VALUES(insurance_amount)
"""
data = [
    (
        row["State"],
        int(row["Year"]),
        int(row["Quarter"]),
        int(row["pincode"]),
        int(row["count"]),
        float(row["amount"])
    )
    for _, row in data_top_insurance_pincode.iterrows()
    if pd.notnull(row["pincode"])   
]

cursor.executemany(insert_query, data)
conn.commit()

cursor.close()
conn.close()

print("✅ Top Insurance Pincode data inserted successfully")

In [50]:
import os
import json
import pandas as pd

top_transaction_path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\transaction\country\india\state"

# ---------------- DISTRICT ---------------- #
data_top_transaction_district = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'entityName': [],
    'count': [],
    'amount': []
}

# ---------------- PINCODE ---------------- #
data_top_transaction_pincode = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'entityName': [],
    'count': [],
    'amount': []
}

states_list = os.listdir(top_transaction_path)

for i in states_list:
    p_i = os.path.join(top_transaction_path, i)

    if not os.path.isdir(p_i):
        continue

    years = os.listdir(p_i)

    for j in years:
        p_j = os.path.join(p_i, j)

        if not os.path.isdir(p_j):
            continue

        files = sorted(os.listdir(p_j))

        for k in files:
            if not k.endswith('.json'):
                continue

            p_k = os.path.join(p_j, k)

            with open(p_k, 'r') as data:
                dataset = json.load(data)

            quarter = int(k.replace('.json', ''))

            # ---------------- DISTRICTS ---------------- #
            districts = dataset.get('data', {}).get('districts', [])

            for z in districts:
                metric = z.get('metric', {})

                data_top_transaction_district['entityName'].append(z.get('entityName'))
                data_top_transaction_district['count'].append(metric.get('count'))
                data_top_transaction_district['amount'].append(metric.get('amount'))
                data_top_transaction_district['State'].append(i)
                data_top_transaction_district['Year'].append(j)
                data_top_transaction_district['Quarter'].append(quarter)

            # ---------------- PINCODES ---------------- #
            pincodes = dataset.get('data', {}).get('pincodes', [])

            for z in pincodes:
                metric = z.get('metric', {})

                data_top_transaction_pincode['entityName'].append(z.get('entityName'))
                data_top_transaction_pincode['count'].append(metric.get('count'))
                data_top_transaction_pincode['amount'].append(metric.get('amount'))
                data_top_transaction_pincode['State'].append(i)
                data_top_transaction_pincode['Year'].append(j)
                data_top_transaction_pincode['Quarter'].append(quarter)


# Convert to DataFrame
df_district = pd.DataFrame(data_top_transaction_district).drop_duplicates()
df_pincode = pd.DataFrame(data_top_transaction_pincode).drop_duplicates()
df_district["State"] = df_district["State"].str.replace("-", " ")
df_district["State"] = df_district["State"].str.title()
df_district["State"] = df_district["State"].str.strip()
df_district.rename(columns={"entityName": "district"}, inplace=True)

df_pincode["State"] = df_pincode["State"].str.replace("-", " ")
df_pincode["State"] = df_pincode["State"].str.title()
df_pincode["State"] = df_pincode["State"].str.strip()
df_district

,State,Year,Quarter,district,count,amount
0,Andaman & Nicobar Islands,2018,1,south andaman,5688,1.256025e+07
1,Andaman & Nicobar Islands,2018,1,nicobars,528,1.139849e+06
2,Andaman & Nicobar Islands,2018,1,north and middle andaman,442,9.316631e+05
3,Andaman & Nicobar Islands,2018,2,south andaman,9395,2.394824e+07
4,Andaman & Nicobar Islands,2018,2,nicobars,1120,3.072437e+06
...,...,...,...,...,...,...
8291,West Bengal,2024,4,howrah,67496284,1.025764e+11
8292,West Bengal,2024,4,nadia,65274337,1.079320e+11
8293,West Bengal,2024,4,malda,63424613,1.024212e+11
8294,West Bengal,2024,4,hooghly,59676576,9.071383e+10
8295,West Bengal,2024,4,paschim medinipur,58238212,8.431774e+10

In [51]:
df = df_district.copy()

# Convert types safely
df["year"] = pd.to_numeric(df["Year"], errors="coerce")
df["quarter"] = pd.to_numeric(df["Quarter"], errors="coerce")
df["transaction_count"] = pd.to_numeric(df["count"], errors="coerce")
df["transaction_amount"] = pd.to_numeric(df["amount"], errors="coerce")

# Drop bad rows
df = df.dropna(subset=["year", "quarter", "district"])

# Final column selection
df = df[["State", "year", "quarter", "district", "transaction_count", "transaction_amount"]]

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()
insert_query = """
INSERT INTO top_transaction_district
(state, year, quarter, district, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""

# SAFE INSERT (handles nulls)
data = [
    (
        row["State"],
        int(row["Year"]) if pd.notnull(row["Year"]) else None,
        int(row["Quarter"]) if pd.notnull(row["Quarter"]) else None,
        row["district"],
        int(row["count"]) if pd.notnull(row["count"]) else 0,
        float(row["amount"]) if pd.notnull(row["amount"]) else 0.0
    )
    for _, row in df_district.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()

cursor.close()
conn.close()

print("✅ Top Transaction District data inserted successfully")

In [ ]:

df_pincode.rename(columns={"entityName": "pincode"}, inplace=True)
df_pincode

In [ ]:
df = df_pincode.copy()

df["year"] = pd.to_numeric(df["Year"], errors="coerce")
df["quarter"] = pd.to_numeric(df["Quarter"], errors="coerce")
df["pincode"] = pd.to_numeric(df["pincode"], errors="coerce")
df["transaction_count"] = pd.to_numeric(df["count"], errors="coerce")
df["transaction_amount"] = pd.to_numeric(df["amount"], errors="coerce")

# Remove bad rows
df = df.dropna(subset=["year", "quarter", "pincode"])

# Final structure
df = df[["State", "year", "quarter", "pincode", "transaction_count", "transaction_amount"]]

In [ ]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()

insert_query = """
INSERT INTO top_transaction_pincode
(state, year, quarter, pincode, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""

# SAFE DATA INSERT (handles nulls)
data = [
    (
        str(row["State"]),
        int(row["year"]),
        int(row["quarter"]),
        int(row["pincode"]),
        int(row["transaction_count"]) if pd.notnull(row["transaction_count"]) else 0,
        float(row["transaction_amount"]) if pd.notnull(row["transaction_amount"]) else 0.0
    )
    for _, row in df.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()

cursor.close()
conn.close()

print("✅ Top Transaction Pincode data inserted successfully")

In [ ]:
import os
import json
import pandas as pd

# -------- PATHS -------- #
state_level_path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\transaction\country\india"
district_pincode_path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\transaction\country\india\state"

# -------- MASTER DATA -------- #
combined_data = {
    'Level': [],
    'State': [],
    'Year': [],
    'Quarter': [],
    'entityName': [],
    'count': [],
    'amount': []
}

# ================================
# ✅ 1. STATES DATA (India level)
# ================================
years = os.listdir(state_level_path)

for y in years:
    y_path = os.path.join(state_level_path, y)

    if not os.path.isdir(y_path):
        continue

    files = sorted(os.listdir(y_path))

    for f in files:
        if not f.endswith('.json'):
            continue

        file_path = os.path.join(y_path, f)

        with open(file_path, 'r') as data:
            dataset = json.load(data)

        quarter = int(f.replace('.json', ''))

        states = dataset.get('data', {}).get('states', [])

        for z in states:
            metric = z.get('metric', {})

            combined_data['Level'].append('State')
            combined_data['State'].append(z.get('entityName'))  # same as entity
            combined_data['Year'].append(y)
            combined_data['Quarter'].append(quarter)
            combined_data['entityName'].append(z.get('entityName'))
            combined_data['count'].append(metric.get('count'))
            combined_data['amount'].append(metric.get('amount'))


# =====================================
# ✅ 2. DISTRICT + PINCODE (State level)
# =====================================
states_list = os.listdir(district_pincode_path)

for i in states_list:
    p_i = os.path.join(district_pincode_path, i)

    if not os.path.isdir(p_i):
        continue

    years = os.listdir(p_i)

    for j in years:
        p_j = os.path.join(p_i, j)

        if not os.path.isdir(p_j):
            continue

        files = sorted(os.listdir(p_j))

        for k in files:
            if not k.endswith('.json'):
                continue

            file_path = os.path.join(p_j, k)

            with open(file_path, 'r') as data:
                dataset = json.load(data)

            quarter = int(k.replace('.json', ''))

            # -------- DISTRICTS -------- #
            districts = dataset.get('data', {}).get('districts', [])

            for z in districts:
                metric = z.get('metric', {})

                combined_data['Level'].append('District')
                combined_data['State'].append(i)
                combined_data['Year'].append(j)
                combined_data['Quarter'].append(quarter)
                combined_data['entityName'].append(z.get('entityName'))
                combined_data['count'].append(metric.get('count'))
                combined_data['amount'].append(metric.get('amount'))

            # -------- PINCODES -------- #
            pincodes = dataset.get('data', {}).get('pincodes', [])

            for z in pincodes:
                metric = z.get('metric', {})

                combined_data['Level'].append('Pincode')
                combined_data['State'].append(i)
                combined_data['Year'].append(j)
                combined_data['Quarter'].append(quarter)
                combined_data['entityName'].append(z.get('entityName'))
                combined_data['count'].append(metric.get('count'))
                combined_data['amount'].append(metric.get('amount'))


# ================================
# ✅ FINAL DATAFRAME
# ================================
final_df = pd.DataFrame(combined_data).drop_duplicates()
final_df["State"] = final_df["State"].str.replace("-", " ")
final_df["State"] = final_df["State"].str.title()
final_df["State"] = final_df["State"].str.strip()
final_df.rename(columns={"entityName": "entity_name"}, inplace=True)

final_df

,Level,State,Year,Quarter,entity_name,count,amount
0,State,Maharashtra,2018,1,maharashtra,16387034,2.171161e+10
1,State,Uttar Pradesh,2018,1,uttar pradesh,12537805,1.393997e+10
2,State,Karnataka,2018,1,karnataka,12016899,1.921790e+10
3,State,West Bengal,2018,1,west bengal,11710225,1.062598e+10
4,State,Andhra Pradesh,2018,1,andhra pradesh,9039585,1.199628e+10
...,...,...,...,...,...,...,...
18570,Pincode,West Bengal,2024,4,711101,6753348,1.049483e+10
18571,Pincode,West Bengal,2024,4,700059,6662715,8.009476e+09
18572,Pincode,West Bengal,2024,4,700039,6575693,9.018748e+09
18573,Pincode,West Bengal,2024,4,734001,6432082,8.996529e+09
18574,Pincode,West Bengal,2024,4,733134,6313560,1.050259e+10

In [53]:
df = final_df.copy()

df["year"] = pd.to_numeric(df["Year"], errors="coerce")
df["quarter"] = pd.to_numeric(df["Quarter"], errors="coerce")
df["transaction_count"] = pd.to_numeric(df["count"], errors="coerce")
df["transaction_amount"] = pd.to_numeric(df["amount"], errors="coerce")

df = df.dropna(subset=["year", "quarter", "entity_name", "Level"])


df = df[["Level", "State", "year", "quarter", "entity_name", "transaction_count", "transaction_amount"]]

In [ ]:

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Annusingh123@",
    database="phonepe_db"
)

cursor = conn.cursor()
insert_query = """
INSERT INTO combined_top_transactions
(level, state, year, quarter, entity_name, transaction_count, transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
transaction_count = VALUES(transaction_count),
transaction_amount = VALUES(transaction_amount)
"""
data = [
    (
        str(row["Level"]),
        str(row["State"]),
        int(row["year"]),
        int(row["quarter"]),
        str(row["entity_name"]),
        int(row["transaction_count"]) if pd.notnull(row["transaction_count"]) else 0,
        float(row["transaction_amount"]) if pd.notnull(row["transaction_amount"]) else 0.0
    )
    for _, row in df.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()

In [54]:
import os
import json
import pandas as pd

path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\user\country\india\state"

data_top_user = {
    'Level': [],
    'State': [],
    'Year': [],
    'Quarter': [],
    'entityName': [],
    'registeredUsers': []
}

states_list = os.listdir(path)

for i in states_list:
    p_i = os.path.join(path, i)

    if not os.path.isdir(p_i):
        continue

    years = os.listdir(p_i)

    for j in years:
        p_j = os.path.join(p_i, j)

        if not os.path.isdir(p_j):
            continue

        files = sorted(os.listdir(p_j))

        for k in files:
            if not k.endswith('.json'):
                continue

            file_path = os.path.join(p_j, k)

            with open(file_path, 'r') as data:
                dataset = json.load(data)

            quarter = int(k.replace('.json', ''))

            # -------- DISTRICTS -------- #
            districts = dataset.get('data', {}).get('districts', [])

            for z in districts:
                data_top_user['Level'].append('District')
                data_top_user['State'].append(i)
                data_top_user['Year'].append(j)
                data_top_user['Quarter'].append(quarter)
                data_top_user['entityName'].append(z.get('name'))
                data_top_user['registeredUsers'].append(z.get('registeredUsers'))

            # -------- PINCODES -------- #
            pincodes = dataset.get('data', {}).get('pincodes', [])

            for z in pincodes:
                data_top_user['Level'].append('Pincode')
                data_top_user['State'].append(i)
                data_top_user['Year'].append(j)
                data_top_user['Quarter'].append(quarter)
                data_top_user['entityName'].append(z.get('name'))
                data_top_user['registeredUsers'].append(z.get('registeredUsers'))


df_top_user = pd.DataFrame(data_top_user).drop_duplicates()
df_top_user["State"] = df_top_user["State"].str.replace("-", " ")
df_top_user["State"] = df_top_user["State"].str.title()
df_top_user["State"] = df_top_user["State"].str.strip()
df_top_user
df_top_user.rename(columns={"entityName": "entity_name"}, inplace=True)

In [ ]:
df = df_top_user.copy()

df["year"] = pd.to_numeric(df["Year"], errors="coerce")
df["quarter"] = pd.to_numeric(df["Quarter"], errors="coerce")
df["registered_users"] = pd.to_numeric(df["registeredUsers"], errors="coerce")


df = df.dropna(subset=["year", "quarter", "entity_name"])


df = df[["Level", "State", "year", "quarter", "entity_name", "registered_users"]]

In [ ]:
insert_query = """
INSERT INTO top_user
(level, state, year, quarter, entity_name, registered_users)
VALUES (%s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
registered_users = VALUES(registered_users)
"""
data = [
    (
        str(row["Level"]),
        str(row["State"]),
        int(row["year"]),
        int(row["quarter"]),
        str(row["entity_name"]),
        int(row["registered_users"]) if pd.notnull(row["registered_users"]) else 0
    )
    for _, row in df.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()

In [55]:
import os
import json
import pandas as pd

path = r"C:\Users\DELL\OneDrive\Desktop\phonepe_project\data\top\user\country\india\state"

data_user_district = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'registeredUsers': []
}

states_list = os.listdir(path)

for i in states_list:
    p_i = os.path.join(path, i)

    if not os.path.isdir(p_i):
        continue

    years = os.listdir(p_i)

    for j in years:
        p_j = os.path.join(p_i, j)

        if not os.path.isdir(p_j):
            continue

        files = sorted(os.listdir(p_j))

        for k in files:
            if not k.endswith('.json'):
                continue

            file_path = os.path.join(p_j, k)

            with open(file_path, 'r') as data:
                dataset = json.load(data)

            quarter = int(k.replace('.json', ''))

            districts = dataset.get('data', {}).get('districts', [])

            for z in districts:
                data_user_district['State'].append(i)
                data_user_district['Year'].append(j)
                data_user_district['Quarter'].append(quarter)
                data_user_district['District'].append(z.get('name'))
                data_user_district['registeredUsers'].append(z.get('registeredUsers'))

df_user_district = pd.DataFrame(data_user_district).drop_duplicates()
df_user_district["State"] = df_user_district["State"].str.replace("-", " ")
df_user_district["State"] = df_user_district["State"].str.title()
df_user_district["State"] = df_user_district["State"].str.strip()
df_user_district.rename(columns={"registeredUsers": "registered_users"}, inplace=True)
df_user_district

,State,Year,Quarter,District,registered_users
0,Andaman & Nicobar Islands,2018,1,south andaman,5846
1,Andaman & Nicobar Islands,2018,1,north and middle andaman,632
2,Andaman & Nicobar Islands,2018,1,nicobars,262
3,Andaman & Nicobar Islands,2018,2,south andaman,8143
4,Andaman & Nicobar Islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,West Bengal,2024,4,hooghly,1957356
8292,West Bengal,2024,4,nadia,1861738
8293,West Bengal,2024,4,purba medinipur,1717074
8294,West Bengal,2024,4,paschim medinipur,1522845
8295,West Bengal,2024,4,paschim bardhaman,1468252

In [ ]:
df = df_user_district.copy()

df["year"] = pd.to_numeric(df["Year"], errors="coerce")
df["quarter"] = pd.to_numeric(df["Quarter"], errors="coerce")
df["registered_users"] = pd.to_numeric(df["registered_users"], errors="coerce")


df = df.dropna(subset=["year", "quarter", "District"])


df = df[["State", "year", "quarter", "District", "registered_users"]]

In [ ]:
insert_query = """
INSERT INTO user_district
(state, year, quarter, district, registered_users)
VALUES (%s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
registered_users = VALUES(registered_users)
"""

data = [
    (
        str(row["State"]),
        int(row["year"]),
        int(row["quarter"]),
        str(row["District"]),
        int(row["registered_users"]) if pd.notnull(row["registered_users"]) else 0
    )
    for _, row in df.iterrows()
]
cursor.executemany(insert_query, data)
conn.commit()

In [ ]:
data_user_pincode = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Pincode': [],
    'registeredUsers': []
}

states_list = os.listdir(path)

for i in states_list:
    p_i = os.path.join(path, i)

    if not os.path.isdir(p_i):
        continue

    years = os.listdir(p_i)

    for j in years:
        p_j = os.path.join(p_i, j)

        if not os.path.isdir(p_j):
            continue

        files = sorted(os.listdir(p_j))

        for k in files:
            if not k.endswith('.json'):
                continue

            file_path = os.path.join(p_j, k)

            with open(file_path, 'r') as data:
                dataset = json.load(data)

            quarter = int(k.replace('.json', ''))

            pincodes = dataset.get('data', {}).get('pincodes', [])

            for z in pincodes:
                data_user_pincode['State'].append(i)
                data_user_pincode['Year'].append(j)
                data_user_pincode['Quarter'].append(quarter)
                data_user_pincode['Pincode'].append(z.get('name'))
                data_user_pincode['registeredUsers'].append(z.get('registeredUsers'))

df_user_pincode = pd.DataFrame(data_user_pincode).drop_duplicates()
df_user_pincode
df_user_pincode["State"] = df_user_pincode["State"].str.replace("-", " ")
df_user_pincode["State"] = df_user_pincode["State"].str.title()
df_user_pincode["State"] = df_user_pincode["State"].str.strip()
df_user_pincode.rename(columns={
    "Pincode": "pincode",
    "registeredUsers": "registered_users"
}, inplace=True)
df_user_pincode

In [ ]:
df = df_user_pincode.copy()

df["year"] = pd.to_numeric(df["Year"], errors="coerce")
df["quarter"] = pd.to_numeric(df["Quarter"], errors="coerce")
df["pincode"] = pd.to_numeric(df["pincode"], errors="coerce")
df["registered_users"] = pd.to_numeric(df["registered_users"], errors="coerce")


df = df.dropna(subset=["year", "quarter", "pincode"])

df = df[["State", "year", "quarter", "pincode", "registered_users"]]

In [ ]:
insert_query = """
INSERT INTO user_pincode
(state, year, quarter, pincode, registered_users)
VALUES (%s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
registered_users = VALUES(registered_users)
"""
data = [
    (
        str(row["State"]),
        int(row["year"]),
        int(row["quarter"]),
        int(row["pincode"]),
        int(row["registered_users"]) if pd.notnull(row["registered_users"]) else 0
    )
    for _, row in df.iterrows()
]

cursor.executemany(insert_query, data)
conn.commit()